### ISSUE TITLE
Hello, marvelous idea, will the code be released?

### ISSUE THREAD

**Issue by BinhuiXie** [munanning/MADA#1]

**Comment by munanning** [comment]
Exactly. But it will take some time, because of tedious and heavy jobs in the company.
BTW, I greatly recommend the codes of Microsoft, https://github.com/microsoft/ProDA. We share similar ideas, but their codes is much stronger than mine.

**Comment by BinhuiXie** [comment]
Thank you very much for your prompt reply! Looking forward to code sharing.

**Comment by munanning** [comment]
Now the codes are finally released. Sorry for the delay.
