### ISSUE TITLE
If a image not containes all the categories, how to 'connecting the vectors of all categories into a long vector'?

### ISSUE THREAD

**Issue by luyvlei** [munanning/MADA#2]
As I understand, MADA need to generate a image-level featurte vector with the mean vector of all classes in a image. But if a category is missing in a picture(in fact it is a common phenomenon), how to generate the vector?

**Comment by BinhuiXie** [comment]
> As I understand, MADA need to generate a image-level featurte vector with the mean vector of all classes in a image. But if a category is missing in a picture(in fact it is a common phenomenon), how to generate the vector?

In my opinion, you can fill with zeros for absent classes in an image.

**Comment by luyvlei** [comment]
It should be the case. Then the k-means will cluster the images with the same category(or missing the same category) into a cluster.
