### ISSUE TITLE
Request of Video/Slides

### ISSUE THREAD

**Issue by cliangyu** [munanning/MADA#4]
Appreciate this nicely presented paper.

As this is accepted as oral paper, I look for any video or slides as publication material to introduce this paper to my colleagues. Thank you!

**Comment by munanning** [comment]
I'm glad you are interested in out work.

Here is the [[PPT](https://docs.google.com/presentation/d/1sJQ0OtPH6PhDC5W4BrVGvViit7crao2y/edit?usp=sharing&ouid=108503405808129646625&rtpof=true&sd=true)].

I also update the slides in README.

**Comment by cliangyu** [comment]
Thank you for the slides!
